# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-21 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField()),
                ('grade', models.IntegerField()),
                ('alimony', models.IntegerField()),
                ('sourceOfExpense', models.IntegerField()),
                ('costType', models.IntegerField()),
                ('costTypeCount', models.IntegerField()),
                ('record', models.IntegerField()),
                ('plan', models.IntegerField()),
                ('demand', models.IntegerField()),
                ('measure', models.IntegerField()),
            ],
        ),
    ]
