# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-21 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='costType',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='result',
            name='costTypeCount',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='result',
            name='demand',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='result',
            name='measure',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='result',
            name='plan',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='result',
            name='record',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='result',
            name='sourceOfExpense',
            field=models.CharField(max_length=64),
        ),
    ]
